name: Build Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'front-end-nextjs/**'
        
jobs:        
  build-frondend:
    name: Build Image
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-southeast-2
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: "qr-generator-frontend"
        IMAGE_TAG: ${{ github.sha }}
        DOCKERFILE: "front-end-nextjs/dockerfile"
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $DOCKERFILE .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG